### ISSUE TITLE
Dependency is throwing error in ubuntu machine

### ISSUE THREAD

**Issue by pankaj805** [jtassin/pending-xhr-puppeteer#24]
Running node service using babel and pm2 on ubuntu (Ubuntu 16.04.4 LTS)
Node version - 6.x

/srv/deployments/profile-service/node_modules/pending-xhr-puppeteer/lib/index.js:19
        );
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Module._extensions..js (module.js:586:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/deployments/profile-service/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/deployments/profile-service/commons/utils/DarbyHelper.js:9:1)
    at Module._compile (module.js:577:32)
    at loader (/srv/deployments/profile-service/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/deployments/profile-service/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

**Comment by pankaj805** [comment]
It got fixed when i upgraded the node version to 8.15.1
